//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhose
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimateData
    {
        public int Id { get; set; }
        public int GreenhouseId { get; set; }
        public int Temperature { get; set; }
        public decimal Humidity { get; set; }
        public decimal Light { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Greenhouses Greenhouses { get; set; }
    }
}
