//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhose
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crops()
        {
            this.PlantingZones = new HashSet<PlantingZones>();
            this.PracticeTemplates = new HashSet<PracticeTemplates>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public int GrowthDays { get; set; }
        public int OptimalTemperature { get; set; }
        public decimal OptimalHumidity { get; set; }
    
        public virtual Type_Crops Type_Crops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantingZones> PlantingZones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeTemplates> PracticeTemplates { get; set; }
    }
}
