//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhose
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Greenhouse_AtenaEntities : DbContext
    {
        public Greenhouse_AtenaEntities()
            : base("name=Greenhouse_AtenaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClimateData> ClimateData { get; set; }
        public virtual DbSet<Crops> Crops { get; set; }
        public virtual DbSet<Greenhouses> Greenhouses { get; set; }
        public virtual DbSet<PlantingZones> PlantingZones { get; set; }
        public virtual DbSet<PracticeTemplates> PracticeTemplates { get; set; }
        public virtual DbSet<Type_Crops> Type_Crops { get; set; }
        public virtual DbSet<WorkPlans> WorkPlans { get; set; }
        public virtual DbSet<WorkTasks> WorkTasks { get; set; }
    }
}
