//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhose
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantingZones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantingZones()
        {
            this.WorkTasks = new HashSet<WorkTasks>();
        }
    
        public int Id { get; set; }
        public int GreenhouseId { get; set; }
        public int CropId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> ExpectedHarvestDate { get; set; }
        public string Status { get; set; }
        public int Area { get; set; }
    
        public virtual Crops Crops { get; set; }
        public virtual Greenhouses Greenhouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTasks> WorkTasks { get; set; }
    }
}
