//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhose
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTasks
    {
        public int Id { get; set; }
        public int WorkPlanId { get; set; }
        public Nullable<int> PlantingZoneId { get; set; }
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Status { get; set; }
        public string AssignedTo { get; set; }
        public string Comments { get; set; }
    
        public virtual PlantingZones PlantingZones { get; set; }
        public virtual WorkPlans WorkPlans { get; set; }
    }
}
